from vgmdb.theme import Theme

Thriller = Theme(20)
SciFi = Theme(18)
Action = Theme(1)
Horror = Theme(19)
Survial = Theme(21)
Fantasy = Theme(17)
History = Theme(22)
Stealth = Theme(23)
Comedy = Theme(27)
Business = Theme(28)
Drama = Theme(31)
NonFiction = Theme(32)
Kids = Theme(35)
Sandbox = Theme(33)
OpenWorld = Theme(38)
Warfare = Theme(39)
FourX = Theme(41)
Education = Theme(34)
Mystery = Theme(43)
Party = Theme(40)
Romance = Theme(44)
Erotic = Theme(42)