from vgmdb.genre import Genre

PointAndClick = Genre(2)
Fighting = Genre(4)
Shooter = Genre(5)
Music = Genre(7)
Platform = Genre(8)
Puzzle = Genre(9)
Racing = Genre(10)
RTS = Genre(11)
RPG = Genre(12)
Simulator = Genre(13)
Sport = Genre(14)
Strategy = Genre(15)
TBS = Genre(16)
Tactical = Genre(24)
HackAndSlash = Genre(25)
Pinball = Genre(30)
Adventure = Genre(31)
Arcade = Genre(33)
VisualNovel = Genre(34)
Board = Genre(35)
MOBA = Genre(36)